use_frameworks!
platform :ios, '10.0'
source "https://github.com/OpenVS/OVSKit-Specs.git"

target 'OVSKit_Example' do
	pod 'OVSKit', :path => '../'
  target 'OVSKit_Tests' do
    inherit! :search_paths
  end
end
