//
//  OVSThemeCodes.h
//  OVSKit
//
//  Created by Xu Liu on 2017-06-08.
//  Copyright © 2017 The Top AI Technology Inc. All rights reserved.
//
// In this file we have defined default theme codes for the OVSApp to use

#define OVS_THEME_DISCLAIMER @"OVS_THEME_DISCLAIMER"
#define OVS_THEME_DISCLAIMER_LBL_TITLE @"OVS_THEME_DISCLAIMER_LBL_TITLE"
#define OVS_THEME_DISCLAIMER_LBL_AGREE_TITLE @"OVS_THEME_DISCLAIMER_LBL_AGREE_TITLE"
#define OVS_THEME_DISCLAIMER_IMG_AGREE @"OVS_THEME_DISCLAIMER_IMG_AGREE"
#define OVS_THEME_DISCLAIMER_VIW_CONTENT @"OVS_THEME_DISCLAIMER_VIW_CONTENT"

//TUTORIAL_WELCOME
#define OVS_THEME_TUTORIAL_WELCOME @"OVS_THEME_TUTORIAL_WELCOME"
#define OVS_THEME_TUTORIAL_WELCOME_IMG @"OVS_THEME_TUTORIAL_WELCOME_IMG"
#define OVS_THEME_TUTORIAL_WELCOME_TITLE @"OVS_THEME_TUTORIAL_WELCOME_TITLE"
#define OVS_THEME_TUTORIAL_WELCOME_DETAILS @"OVS_THEME_TUTORIAL_WELCOME_DETAILS"

//TUTORIAL_LOCATION
#define OVS_THEME_TUTORIAL_LOCATION @"OVS_THEME_TUTORIAL_LOCATION"
#define OVS_THEME_TUTORIAL_LOCATION_TITLE @"OVS_THEME_TUTORIAL_LOCATION_TITLE"
#define OVS_THEME_TUTORIAL_LOCATION_DETAILS @"OVS_THEME_TUTORIAL_LOCATION_DETAILS"
#define OVS_THEME_TUTORIAL_LOCATION_ELB_BUTTON @"OVS_THEME_TUTORIAL_LOCATION_ELB_BUTTON"
#define OVS_THEME_TUTORIAL_LOCATION_IMG @"OVS_THEME_TUTORIAL_LOCATION_IMG"

//TUTORIAL_PUSH
#define OVS_THEME_TUTORIAL_PUSH @"OVS_THEME_TUTORIAL_PUSH"
#define OVS_THEME_TUTORIAL_PUSH_TITLE @"OVS_THEME_TUTORIAL_PUSH_TITLE"
#define OVS_THEME_TUTORIAL_PUSH_DETAILS @"OVS_THEME_TUTORIAL_PUSH_DETAILS"
#define OVS_THEME_TUTORIAL_PUSH_ELB_BUTTON @"OVS_THEME_TUTORIAL_PUSH_ELB_BUTTON"
#define OVS_THEME_TUTORIAL_PUSH_IMG @"OVS_THEME_TUTORIAL_PUSH_IMG"

//TUTORIAL_STARTED
#define OVS_THEME_TUTORIAL_GET_STARTED @"OVS_THEME_TUTORIAL_GET_STARTED"
#define OVS_THEME_TUTORIAL_GET_STARTED_DETAILS @"OVS_THEME_TUTORIAL_GET_STARTED_DETAILS"
#define OVS_THEME_TUTORIAL_GET_STARTED_BUTTON @"OVS_THEME_TUTORIAL_GET_STARTED_BUTTON"
#define OVS_THEME_TUTORIAL_GET_STARTED_IMG @"OVS_THEME_TUTORIAL_GET_STARTED_IMG"



//TUTORIAL_PAGE_INDICATOR
#define OVS_THEME_TUTORIAL_PAGE_INDICATOR @"OVS_THEME_TUTORIAL_PAGE_INDICATOR"

//LOGIN_PAGE
#define OVS_THEME_LOGIN @"OVS_THEME_LOGIN"
#define OVS_THEME_LOGIN_LBL_ERROR @"OVS_THEME_LOGIN_LBL_ERROR"
#define OVS_THEME_LOGIN_LGN_BUTTON @"OVS_THEME_LOGIN_LGN_BUTTON"
#define OVS_THEME_LOGIN_RGS_BUTTON @"OVS_THEME_LOGIN_RGS_BUTTON"
#define OVS_THEME_LOGIN_BTN_VERSION @"OVS_THEME_LOGIN_BTN_VERSION"
#define OVS_THEME_LOGIN_USERNAME @"OVS_THEME_LOGIN_USERNAME"
#define OVS_THEME_LOGIN_PASSWORD @"OVS_THEME_LOGIN_PASSWORD"

//WAITING_VIEW
#define OVS_THEME_WAITING_VIEW_HOLDER @"OVS_THEME_WAITING_VIEW_HOLDER"
#define OVS_THEME_WAITING_VIEW_SPINER @"OVS_THEME_WAITING_VIEW_SPINER"
#define OVS_THEME_WAITING_VIEW_TITLE @"OVS_THEME_WAITING_VIEW_TITLE"
#define OVS_THEME_WAITING_VIEW @"OVS_THEME_WAITING_VIEW"


//DIALOGBOX
#define OVS_THEME_DIALOGBOX @"OVS_THEME_DIALOGBOX"
#define OVS_THEME_DIALOGBOX_HOLDER @"OVS_THEME_DIALOGBOX_HOLDER"

//REGISTRATION_FORM
#define OVS_THEME_REGISTRATION_FORM @"OVS_THEME_REGISTRATION_FORM"
#define OVS_THEME_REGISTRATION_FORM_TITLE @"OVS_THEME_REGISTRATION_FORM_TITLE"
#define OVS_THEME_REGISTRATION_FORM_INFO @"OVS_THEME_REGISTRATION_FORM_INFO"
#define OVS_THEME_REGISTRATION_FORM_HOLDER @"OVS_THEME_REGISTRATION_FORM_HOLDER"
#define OVS_THEME_REGISTRATION_FORM_HOLDER_LBL @"OVS_THEME_REGISTRATION_FORM_HOLDER_LBL"
#define OVS_THEME_REGISTRATION_FORM_HOLDER_TXT @"OVS_THEME_REGISTRATION_FORM_HOLDER_TXT"
#define OVS_THEME_REGISTRATION_FORM_HOLDER_BTN @"OVS_THEME_REGISTRATION_FORM_HOLDER_BTN"
#define OVS_THEME_REGISTRATION_FORM_BTN_CANCEL @"OVS_THEME_REGISTRATION_FORM_BTN_CANCEL"
#define OVS_THEME_REGISTRATION_FORM_BTN_REGISTER @"OVS_THEME_REGISTRATION_FORM_BTN_REGISTER"

//LOGIN_MENU
#define OVS_THEME_LOGIN_MENU_STAR @"OVS_THEME_LOGIN_MENU_STAR"
#define OVS_THEME_LOGIN_MENU_LOGOUT @"OVS_THEME_LOGIN_MENU_LOGOUT"

//SYSTEM_PANEL
#define OVS_THEME_SYSTEM_PANEL_NAVIGATION @"OVS_THEME_SYSTEM_PANEL_NAVIGATION"
#define OVS_THEME_SYSTEM_PANEL_NAVIGATION_TEXT @"OVS_THEME_SYSTEM_PANEL_NAVIGATION_TEXT"

//SYSTEM_LOG
#define OVS_THEME_SYSTEM_LOG_EMAIL_BTN @"OVS_THEME_SYSTEM_LOG_EMAIL_BTN"
#define OVS_THEME_SYSTEM_LOG_FLUSH_BTN @"OVS_THEME_SYSTEM_LOG_FLUSH_BTN"
#define OVS_THEME_SYSTEM_LOG_REFRESH_BTN @"OVS_THEME_SYSTEM_LOG_REFRESH_BTN"
#define OVS_THEME_SYSTEM_LOG_BOTTOM_HOLDER @"OVS_THEME_SYSTEM_LOG_BOTTOM_HOLDER"






